// This file is auto-generated by @hey-api/openapi-ts

export type AppointmentCreate = {
    patient_name: string;
    patient_id_number: string;
    patient_phone: string;
    patient_email?: (string | null);
    appointment_time: string;
    status?: string;
    hospital_id: string;
    doctor_id: string;
};

export type AppointmentPublic = {
    patient_name: string;
    patient_id_number: string;
    patient_phone: string;
    patient_email?: (string | null);
    appointment_time: string;
    status?: string;
    id: string;
    user_id: string;
    hospital_id: string;
    doctor_id: string;
};

export type AppointmentsPublic = {
    data: Array<AppointmentPublic>;
    count: number;
};

export type AppointmentUpdate = {
    status?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DoctorPublic = {
    name: string;
    specialty: string;
    rating?: number;
    id: string;
    hospital_id: string;
};

export type DoctorsPublic = {
    data: Array<DoctorPublic>;
    count: number;
};

export type DoctorTimeSlotPublic = {
    time_slot: string;
    is_available?: boolean;
    id: string;
    doctor_id: string;
};

export type HospitalPublic = {
    name: string;
    address: string;
    id: string;
};

export type HospitalsPublic = {
    data: Array<HospitalPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type UserValidation = {
    name: string;
    id_number: string;
    phone: string;
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AppointmentsValidateUserData = {
    requestBody: UserValidation;
};

export type AppointmentsValidateUserResponse = (Message);

export type AppointmentsGetHospitalsData = {
    limit?: number;
    skip?: number;
};

export type AppointmentsGetHospitalsResponse = (HospitalsPublic);

export type AppointmentsGetHospitalDoctorsData = {
    hospitalId: string;
    limit?: number;
    skip?: number;
};

export type AppointmentsGetHospitalDoctorsResponse = (DoctorsPublic);

export type AppointmentsGetDoctorTimeSlotsData = {
    doctorId: string;
};

export type AppointmentsGetDoctorTimeSlotsResponse = (Array<DoctorTimeSlotPublic>);

export type AppointmentsCreateAppointmentData = {
    requestBody: AppointmentCreate;
};

export type AppointmentsCreateAppointmentResponse = (AppointmentPublic);

export type AppointmentsGetAppointmentsData = {
    limit?: number;
    skip?: number;
};

export type AppointmentsGetAppointmentsResponse = (AppointmentsPublic);

export type AppointmentsGetAppointmentData = {
    appointmentId: string;
};

export type AppointmentsGetAppointmentResponse = (AppointmentPublic);

export type AppointmentsUpdateAppointmentData = {
    appointmentId: string;
    requestBody: AppointmentUpdate;
};

export type AppointmentsUpdateAppointmentResponse = (AppointmentPublic);

export type AppointmentsDeleteAppointmentData = {
    appointmentId: string;
};

export type AppointmentsDeleteAppointmentResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);